# Base ubuntu build (latest).
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu

# Update packages.
RUN apt-get update

# Set the default shell to zsh
ENV SHELL=/usr/bin/zsh

# Running everything under zsh
SHELL ["/usr/bin/zsh", "-c"]

# Dropping privileges
USER vscode

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source $HOME/.cargo/env

# Add uv to shell configuration
RUN echo 'export PATH="/home/vscode/.cargo/bin:$PATH"' >> ~/.zshrc

# Add Sui Move
RUN curl -sSfL https://raw.githubusercontent.com/Mystenlabs/suiup/main/install.sh | sh
RUN yes | /home/vscode/.local/bin/suiup install sui

# Clean up
RUN sudo apt-get autoremove -y && sudo apt-get clean -y